### ISSUE TITLE
Encountered two children with the same key for node views

### ISSUE THREAD

**Issue by ahielanravichandran** [nytimes/react-prosemirror#73] opened 2023-12-13 13:12 UTC
Hey everyone, 

I'm encountering an issue in the latest version (0.4.2). Specifically, when a new node is added, rendered via node views generated with the same keys, I noticed something during my investigation. In the React plugin, even if the key is present, it seems to be added to the new keys map in the apply method. Any insights or suggestions would be greatly appreciated.

You can replicate the issue in this sandbox setup: [StackBlitz - Vite.js](https://stackblitz.com/edit/vitejs-vite-vfl1te?file=src%2FApp.tsx%2Csrc%2FLabel.tsx%2Csrc%2FEditor.tsx%2Csrc%2FApp.css&terminal=dev)

<img width="1427" alt="Screenshot 2023-12-13 at 6 35 25 PM" src="https://github.com/nytimes/react-prosemirror/assets/26704124/c8e4999e-aeeb-4bc1-8e22-5e3cb0e51507">

**Comment by anik-chroniclehq** [comment] 2023-12-13 13:28
We did some digging and found that
- the react plugin generates a new nodeKey if a multiple node maps back to single pos
- the core issue happens when the `registerCallback` in `useNodeViews` is called with the portal for the newly inserted node, it seems to have the same key as it was before `reactPlugin` did its job
  - see: https://github.com/nytimes/react-prosemirror/blob/main/src/hooks/useNodeViews.tsx#L56
  - the newly passed `portal`'s keys also exists in the `oldChildPortals` keys
  - as a hack, I tried checking if the `portal`'s key already existed in `oldChildPortals` and creating + updating a new node key across the plugin + portal, and the errors didn't happen anymore
- was not able to deduce why the portal had the old key unfortunately
- it might be a bit hard to repro in this demo but it consistently happened for us internally whenever inserting a nodeview in between 2 nodeviews
  - for best chances to hit the error, try pressing Enter to insert in between 2 nodes
  - entirely possible that we're doing something wrong, would appreciate any insights

**Comment by smoores-dev** [comment] 2023-12-13 14:01
Thanks for the report, @ahielanravichandran, and for the details, @anik-chroniclehq!

I'm going to dig into this, but:

> the core issue happens when the registerCallback in useNodeViews is called with the portal for the newly inserted node, it seems to have the same key as it was before reactPlugin did its job 

This makes me wonder if this might be related to this issue: https://github.com/nytimes/react-prosemirror/issues/69#issuecomment-1815285694

Specifically:

> The React tree renders because of the state update, but the EditorView's state has not been updated yet, so all of the node views still have references to the nodes from the previous render (this is expected)

Again, I'll take a look, though, and see if something can't be done about it!

**Comment by smoores-dev** [comment] 2023-12-13 14:17
@anik-chroniclehq, since you mentioned being able to reproduce this consistently, could you do me a favor and try to reproduce with the `react()` plugin as the very last in the list? I'm not sure that this matters, but I'm having a lot of trouble reproducing consistently!

**Comment by anik-chroniclehq** [comment] 2023-12-13 14:37
@smoores-dev Yes, I am able to consistently reproduce with `react()` as the very last plugin as well. For more info, what we're basically doing is inserting one node (which is rendered using NodeViews) in between other nodeviews of the same type.

Let me know if you need more info, I'm on the gitter channel as well on w/ display name `sadn1ck`

**Comment by smoores-dev** [comment] 2023-12-13 15:07
I am able to consistently reproduce now. It looks like this specifically happens when the new node is inserted _before_ the old node. The plugin always reassigns the key for node with the higher position, so in this scenario, it actually reassigns the key for the old node, and assigns the old node's old key to the new node. ProseMirror doesn't call the node view's `update` method in this scenario (I suppose this is because only the position has changed), so there's no opportunity for the old node to inform the portal registry that its key has changed, resulting in two nodes with the same key (even though the plugin knows that they should be different).

Still poking around, I suspect that there's a way out of this!

**Comment by smoores-dev** [comment] 2023-12-13 15:38
@anik-chroniclehq  @ahielanravichandran could you give `@nytimes/react-prosemirror@issue73` a shot? I think that (#74) may resolve the issue

**Comment by anik-chroniclehq** [comment] 2023-12-13 15:46
@smoores-dev Yup, that seems to have solved the issue. Thanks so much for looking into this so soon!

**Comment by ahielanravichandran** [comment] 2023-12-13 18:08
@smoores-dev Really appreciate you for solving this. Thanks!

**Closed** 2024-02-01 23:49 UTC
