### ISSUE TITLE
TypeError: root.getSelection is not a function

### ISSUE THREAD

**Issue by legitmaxwu** [nytimes/react-prosemirror#149] opened 2024-12-18 03:01 UTC
Hi, thanks for this library! I like the idea of using React to render the editor.

I'm trying to set it up in my Next.js project. I have `@nytimes/react-prosemirror@0.7.0-next.11` installed, and I have a minimal setup:

```tsx
"use client";

import { EditorState } from "prosemirror-state";
import {
  ProseMirror,
  ProseMirrorDoc,
  reactKeys,
} from "@nytimes/react-prosemirror";
import { schema } from "prosemirror-schema-basic";

import dynamic from "next/dynamic";

const ProseMirrorEditor = dynamic(
  () =>
    Promise.resolve(() => (
      <ProseMirror
        defaultState={EditorState.create({ schema, plugins: [reactKeys()] })}
      >
        <ProseMirrorDoc />
      </ProseMirror>
    )),
  { ssr: false },
);

export default ProseMirrorEditor;
```

However, I'm getting the following error when I try to interact with the editor:

```
Unhandled Runtime Error
TypeError: root.getSelection is not a function

Call Stack
NodeViewDesc.setSelection
node_modules/.pnpm/@nytimes+react-prosemirror@0.7.0-next.11_prosemirror-model@1.24.0_prosemirror-state@1.4.3_pro_c2gfulo3vqcyszuxgmzn63zkkq/node_modules/@nytimes/react-prosemirror/dist/esm/viewdesc.js (306:29)
NodeViewDesc.setSelection
node_modules/.pnpm/@nytimes+react-prosemirror@0.7.0-next.11_prosemirror-model@1.24.0_prosemirror-state@1.4.3_pro_c2gfulo3vqcyszuxgmzn63zkkq/node_modules/@nytimes/react-prosemirror/dist/esm/viewdesc.js (301:57)
selectionToDOM
node_modules/.pnpm/prosemirror-view@1.37.1/node_modules/prosemirror-view/dist/index.js (2247:22)
ReactEditorView.updateStateInner
node_modules/.pnpm/prosemirror-view@1.37.1/node_modules/prosemirror-view/dist/index.js (5409:17)
ReactEditorView.update
node_modules/.pnpm/prosemirror-view@1.37.1/node_modules/prosemirror-view/dist/index.js (5324:14)
ReactEditorView.update
node_modules/.pnpm/@nytimes+react-prosemirror@0.7.0-next.11_prosemirror-model@1.24.0_prosemirror-state@1.4.3_pro_c2gfulo3vqcyszuxgmzn63zkkq/node_modules/@nytimes/react-prosemirror/dist/esm/hooks/useEditor.js (86:15)
ReactEditorView.runPendingEffects
node_modules/.pnpm/@nytimes+react-prosemirror@0.7.0-next.11_prosemirror-model@1.24.0_prosemirror-state@1.4.3_pro_c2gfulo3vqcyszuxgmzn63zkkq/node_modules/@nytimes/react-prosemirror/dist/esm/hooks/useEditor.js (82:18)
<unknown>
node_modules/.pnpm/@nytimes+react-prosemirror@0.7.0-next.11_prosemirror-model@1.24.0_prosemirror-state@1.4.3_pro_c2gfulo3vqcyszuxgmzn63zkkq/node_modules/@nytimes/react-prosemirror/dist/esm/hooks/useEditor.js (256:19)
```

Any idea why this might be the case?

**Comment by smoores-dev** [comment] 2024-12-18 03:04
Is this a server-side error or are you seeing this in the browser console?

**Comment by smoores-dev** [comment] 2024-12-18 03:05
(Funny enough, I was _just_ working on SSR in Next.js (#148), but I didn't run into this, which is... odd!)

**Comment by legitmaxwu** [comment] 2024-12-18 03:06
I'm seeing it in the browser console!

**Comment by smoores-dev** [comment] 2024-12-18 03:07
Ok, that makes more sense than in the server logs, at least! What browser are you using?

**Comment by legitmaxwu** [comment] 2024-12-18 03:10
Chrome Version 131.0.6778.140 (Official Build) (arm64)

The error appears when I try to type anything into the editor. If you have an existing setup that works in Next.js I would love to see how it's structured.

**Comment by smoores-dev** [comment] 2024-12-18 03:12
I don't have anything public facing right now, unfortunately :/. But this looks right to me, and I don't see why this would be happening -- that should be running `document.getSelection()` (`root` should be `document`), and all browsers have supported `document.getSelection()` essentially forever.

Would you be able to set a breakpoint in the browser debugger and see what value `root` is?

**Comment by legitmaxwu** [comment] 2024-12-18 03:16
I logged it--It's a `ReactEditorView` object! (for some reason it's hard for me to copy the text)

![image](https://github.com/user-attachments/assets/345de701-3910-4d07-bf00-042501e69bd0)

Thanks so much for your help and quick responses, by the way!

**Comment by legitmaxwu** [comment] 2024-12-18 03:17
Curiously, when I initially focus on the editor (and before typing something / causing the error) `root` is just an element

![image](https://github.com/user-attachments/assets/bde33216-3b77-4e68-9aaa-7e07311a65fe)

**Comment by smoores-dev** [comment] 2024-12-18 03:19
No problem! This is super weird, and almost certainly a bug in React ProseMirror, though I don't know... how?? I'll have to try to reproduce tomorrow and see if I can figure out the cause. Thanks for reporting!

**Comment by smoores-dev** [comment] 2024-12-18 16:39
@legitmaxwu which version of Next.js and React are you using?

**Comment by smoores-dev** [comment] 2024-12-18 16:56
Ah, ok. The short term solution is to downgrade your prosemirror-view version - and internal API that we rely on has changed. Make sure you use the prosemirror-view version that React ProseMirror specifies in its peer dependencies, currently `1.34.2`! I'll open a PR to update to the newer version shortly.

**Comment by smoores-dev** [comment] 2024-12-18 20:47
Great! Glad it's fixed. We do actually pin to a specific version of prosemirror-view for just that reason: https://github.com/nytimes/react-prosemirror/blob/main/package.json#L102 but most package managers don't make it very clear when a peer dep version constraint is violated, unfortunately

**Comment by legitmaxwu** [comment] 2024-12-18 21:01
Oh wow, yeah, my `package.json` had `^1.34.2` so I assumed the peer dependency wasn't pinned haha.

**Comment by smoores-dev** [comment] 2024-12-19 03:26
Going to close this issue! I'll open a PR to bump us up to the latest prosemirror-view

**Closed by smoores-dev** 2024-12-19 03:26 UTC
