### ISSUE TITLE
'mismatched transaction error'  when using prosemirror-tables

### ISSUE THREAD

**Issue by dev-yun** [nytimes/react-prosemirror#58] opened 2023-11-03 08:25 UTC
Hello

I encountered an error when using the library.

### demo

https://github.com/nytimes/react-prosemirror/assets/71367408/40c8826a-835f-489b-8dd8-69e2d486736f

This error occurs when you install the prosmirror-table and use the default resizing plugin.

Initially, I thought it was related to one of the complex editor logics. 

However, when I tested by adding only the most basic functions, I encountered the same error. 
You can find the [test repository here](https://github.com/dev-yun/editor_table).
-  main branch is install react-prosemirror and using prosemirror-table plugin => error occurs 
-  chore_react-prosemirror is remove react-prosemirror and copy react-prosemirror code to local enviroment & using prosemirror-table plugin => works well

### Discovery info

1. When installing react-prosemirror and using the prosemirror-table plugin, a `mismatched transaction error` occurs.

2. When adding react-prosemirror to a local environment and using the prosemirror-table plugin, functions like column resizing work correctly.

3. When deploying an editor library containing the core logic of react-prosemirror to npm and installing it, the same error occurs. (`mismatched transaction error`)

4. Removing the wrapping of the dispatch logic in the editor library containing the core logic of react-prosemirror with flushSync results in normal operation.
  a. In this case, view updates should be performed with `view.updateState(state)` rather than `view.setProps({ state })`.

Thank you

**Comment by smoores-dev** [comment] 2023-11-03 16:56
Thanks for your report @dev-yun! I was able to reproduce this issue on v0.2.3, as long as I used the `state` and `dispatchTransaction` props (as you're doing in your example). There doesn't seem to be an issue with the `defaultState` prop (which I think makes sense). However, the issue seems to be resolved with the change from `batch` to `flushSync`, at least in my demo, so I published a new version (v0.3.0) to npm just now with those changes.

Here's the demo I used to test, which is using the demo code from https://github.com/prosemirrorr/prosemirror-tables: https://github.com/smoores-dev/react-prosemirror-tables-test

You can interact with the demo here: https://smoores-dev.github.io/react-prosemirror-tables-test/

Can you try upgrading to `@nytimes/react-prosemirror@0.3.0` and see if that resolves the issue for you?

**Comment by dev-yun** [comment] 2023-11-04 16:13
I see, I was using the code from version 0.23, and in that code, state synchronization was done using batch instead of flushSync, which caused the issue.

I understand now. After updating to version 0.3, everything works as expected.

Thank you for your response!

**Comment by smoores-dev** [comment] 2023-11-04 16:14
Great, I'm so glad that worked for you!

**Closed by smoores-dev** 2023-11-04 16:14 UTC
